require_paths:
- "C:/Program Files/SketchUp/SketchUp 2021/Tools"
- "C:/Program Files/SketchUp/SketchUp 2020/Tools"
- "C:/Program Files/SketchUp/SketchUp 2019/Tools"
- ruby

require:
- sketchup-api-stubs

reporters:
- rubocop

exclude:
- cext/build/**/*
- third-party/**/*
